server:
  port: 8089
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /api/auth

spring:
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CorpConnect
    username: root
    password: r@@T0000

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        format_sql: true         # to show the sql queries in a readable format rather than single line
        default_schema: CorpConnect       # Ensure schema is set
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  jackson:
    serialization:
      indent_output: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rohanpansara2632@gmail.com
    password: chraojnuutnfzckn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  token-expiration-time:
    user: 28800000      # 8 hours in milliseconds
    admin: 14400000     # 4 hours in milliseconds
  refresh-token-expiration-time:
    user: 144000000     # 40 hours in milliseconds
    admin: 72000000     # 20 hours in milliseconds

colored-logs: true

#cloudinary:
#  api-key: 132918619484761


