INSERT INTO `CorpConnect`.`COMPANY_EMAIL_TEMPLATES`
(`id`,
 `name`,
 `subject`,
 `body`,
 `deleted`,
 `created_date`,
 `created_by`,
 `last_updated_date`,
 `last_updated_by`)
VALUES
(4,
 'new_user_otp_verification',
 'OTP Verification',
 '<!DOCTYPE html>
  <html lang=\"en\">
  <head>
      <meta charset=\"UTF-8\">
      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
      <link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@400;500;600&display=swap\" rel=\"stylesheet\" />
      <title>OTP Verification</title>
      <style>
          body {
              font-family: \"Lato\", sans-serif;
              margin: 0;
              padding: 0;
              background-color: #f4f4f4;
              font-size: 14px;
          }
          .container {
              max-width: 600px;
              margin: 30px auto;
              background: #ffffff;
              padding: 20px;
              border-radius: 8px;
              box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
              text-align: center;
          }
          .logo {
              width: 100px;
              margin-bottom: 20px;
          }
          h2 {
              color: #333;
          }
          p {
              color: #555;
              font-size: 16px;
          }
          .otp {
              display: inline-block;
              font-size: 24px;
              font-weight: bold;
              color: #2c3e50;
              background: #f3f3f3;
              padding: 10px 20px;
              border-radius: 5px;
              letter-spacing: 5px;
              margin: 20px 0;
          }
          .footer {
              margin-top: 20px;
              text-align: center;
              color: #999999;
          }
      </style>
  </head>
  <body>
      <div class=\"container\">
          <img src=\"https://images.seeklogo.com/logo-png/47/2/creative-commons-logo-png_seeklogo-470282.png" alt=\"Company Logo\" class=\"logo\">
          <h2>New User Otp Verification</h2>
          <p>Please verify your email. Use the OTP below to proceed.</p>
          <div class=\"otp\">{{otp}}</div>
          <p>This OTP is valid for 10 minutes. Do not share it with anyone.</p>
          <p>If you didn\'t request this, you can safely ignore this email.</p>
          <div class=\"footer\">
              <p>
                  &copy; {{currentYear}} {{companyName}}. All rights reserved.
              </p>
              <p class=\"auto-message\">
                  This is an autogenerated email, please do not reply.
              </p>
          </div>
      </div>
  </body>
  </html>',
 0,
 NOW(),
 'system',
 NOW(),
 'system');
