INSERT INTO CorpConnect.COMPANY_EMAIL_TEMPLATES
(`id`,
 `name`,
 `subject`,
 `body`,
 `deleted`,
 `created_date`,
 `created_by`,
 `last_updated_date`,
 `last_updated_by`)
VALUES
(2,
 'welcome',
 'Welcome to the Team, {{employeeName}}!',
 '<!DOCTYPE html>
  <html lang=\"en\">
  <head>
      <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@400;500;600&display=swap\" rel=\"stylesheet\" />
    <title>Welcome to the Team!</title>
      <style>
          body {
            font-family: \"Lato\", sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            font-size: 14px;
          }
          .container {
              max-width: 600px;
              margin: 0 auto;
              background-color: #ffffff;
              padding: 20px;
              border-radius: 8px;
              box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
          }
          h1 {
              color: #333333;
              font-size: 24px;
              text-align: center;
          }
          p {
              color: #666666;
              line-height: 1.6;
          }
          .welcome-section {
              background: #0073e6;
              background: -webkit-linear-gradient(to left, #63ace0, #0073e6);
              background: linear-gradient(to left, #63ace0, #0073e6);
              color: white;
              padding: 20px;
              text-align: left;
              border-radius: 8px 8px 0 0;
              text-transform: uppercase;
              margin-bottom: 20px;
          }
          .welcome-section h2 {
              font-size: 22px;
              margin: 0;
          }
          .content {
              padding: 10px 0;
          }
          .highlight-text {
              font-weight: 600;
          }
          .highlight-text.italic-text {
              font-style: italic;
          }
          .button {
              display: inline-block;
              background-color: #0073e6;
              color: white;
              padding: 10px 20px;
              margin: 20px 0;
              text-align: center;
              text-decoration: none;
              border-radius: 5px;
          }
          .button a {
              color: white !important;
              text-decoration: none !important;
          }
          .footer {
              margin-top: 20px;
              text-align: center;
              color: #999999;
          }
          ul>li>a {
              text-decoration: none;
              color: white;
          }
          .auto-message {
              margin-top: 20px;
              font-size: 12px;
              text-align: center;
              color: #999999;
          }
      </style>
  </head>
  <body>
      <div class=\"container\">
          <div class=\"welcome-section\">
              <h2>Welcome to the Team</h2>
          </div>
          <div class=\"content\">
              Dear <span class=\"highlight-text italic-text\">{{employeeName}}</span>,
              <p>
                  Welcome to <strong>{{companyName}}</strong>! We are excited to have you join our team.
                  Your skills and talents will be a great addition to our organization, and we look forward to collaborating with you.
              </p>
              <p>
                  You\'ll be working with some of the best in the industry, and we are sure you\'ll have a meaningful and enjoyable experience.
              </p>
              <p>
                  Below are some quick links to help you get started:
              </p>
              <ul>
                  <li><a href=\"{{employeePortalLink}}\" class=\"button\" style=\"color: white; text-decoration: none;\">Access Your Employee Portal</a></li>
                  <li><a href=\"{{onboardingLink}}\" class=\"button\" style=\"color: white; text-decoration: none;\">Start Your Onboarding</a></li>
                  <li><a href=\"{{contactHRLink}}\" class=\"button\" style=\"color: white; text-decoration: none;\">Contact HR</a></li>
              </ul>
              <p>
                  If you have any questions or need assistance, feel free to reach out to your manager or the HR team.
              </p>
              <p>
                  We\'re glad to have you on board, and we can\'t wait to see the impact you will make!
              </p>
              <p>
                  Best regards,<br>
                  <strong>{{companyName}} Team</strong>
              </p>
          </div>
          <div class=\"footer\">
              <p>
                  &copy; {{currentYear}} {{companyName}}. All rights reserved.
              </p>
              <p class=\"auto-message\">
                  This is an autogenerated email, please do not reply.
              </p>
          </div>
      </div>
  </body>
  </html>',
 0,
 NOW(),
 'system',
 NOW(),
 'system');