CREATE TABLE IF NOT EXISTS CorpConnect.USERS_ATTENDANCE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    ATTENDANCE_DATE DATE NOT NULL,
    TOTAL_HOURS DECIMAL(5, 2) DEFAULT 0.0,
    STATUS VARCHAR(20) DEFAULT 'present',
    REMARKS TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
